// Generated by @wagmi/cli@0.1.6 on 2/17/2023 at 1:39:41 PM
import {
  useContract,
  UseContractConfig,
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig,
} from 'wagmi'
import { WriteContractMode, PrepareWriteContractResult } from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// BanditTreasury
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const banditTreasuryABI = [
  { stateMutability: 'nonpayable', type: 'constructor', inputs: [] },
  { type: 'error', inputs: [], name: 'NOT_MANAGER' },
  { type: 'error', inputs: [], name: 'NOT_WITHDRAWER' },
  { type: 'error', inputs: [], name: 'ZERO_ADDRESS' },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'manager',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_manager', internalType: 'address', type: 'address' }],
    name: 'setManager',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_withdrawer', internalType: 'address', type: 'address' },
      { name: '_allowed', internalType: 'bool', type: 'bool' },
    ],
    name: 'setWithdrawer',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_token', internalType: 'address', type: 'address' },
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_to', internalType: 'address payable', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdrawEth',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'withdrawers',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DumpingBandits
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dumpingBanditsABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: '_rc', internalType: 'address', type: 'address' },
      { name: '_treasury', internalType: 'address', type: 'address' },
    ],
  },
  { type: 'error', inputs: [], name: 'CANT_FINALIZE_YET' },
  { type: 'error', inputs: [], name: 'NOT_OWNER' },
  { type: 'error', inputs: [], name: 'TOO_MANY' },
  { type: 'error', inputs: [], name: 'TOO_MANY_PRIZES' },
  { type: 'error', inputs: [], name: 'WRONG_PRICE' },
  { type: 'error', inputs: [], name: 'ZERO_ADDRESS' },
  { type: 'error', inputs: [], name: 'ZERO_WINNERS' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'roundId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'participantId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ParticipantAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'roundId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Redistribution',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'roundId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'randomness',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'RoundFinalized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'roundId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'RoundStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'everyoneWinsProbability',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetEveryoneWinsProbability',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'finalizerReward',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetFinalizerReward',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'minDuration',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetMinDuration',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'SetOwner',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'price',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetPrice',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'prizes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false,
      },
    ],
    name: 'SetPrizes',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'rc', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'SetRandomnessClient',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'treasury',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'SetTreasury',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'treasuryReserve',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetTreasuryReserve',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Transfer',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'roundId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'prizeId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'prizeAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'WonPrize',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'everyoneWinsProbability',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'finalizeRound',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'finalizerReward',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_owner', internalType: 'address', type: 'address' }],
    name: 'getOwnerTokenIds',
    outputs: [{ name: '', internalType: 'uint256[]', type: 'uint256[]' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'address', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'lastRoundLastTokenId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'minDuration',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [],
    name: 'participate',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'price',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'prizeRank',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'prizes',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'rc',
    outputs: [
      { name: '', internalType: 'contract IRandomnessClient', type: 'address' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'roundId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'roundParticipants',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'roundStartedAt',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'rounds',
    outputs: [
      { name: 'randomness', internalType: 'uint256', type: 'uint256' },
      { name: 'participants', internalType: 'uint256', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address' },
      { name: 'approved', internalType: 'bool', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: '_everyoneWinsProbability',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    name: 'setEveryoneWinsProbability',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_finalizerReward', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setFinalizerReward',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_minDuration', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setMinDuration',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_owner', internalType: 'address', type: 'address' }],
    name: 'setOwner',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_price', internalType: 'uint256', type: 'uint256' }],
    name: 'setPrice',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_prizes', internalType: 'uint256[]', type: 'uint256[]' }],
    name: 'setPrizes',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_rc', internalType: 'address', type: 'address' }],
    name: 'setRandomnessClient',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_treasury', internalType: 'address', type: 'address' }],
    name: 'setTreasury',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_treasuryReserve', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setTreasuryReserve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenIdRound',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenInfo',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'treasury',
    outputs: [
      { name: '', internalType: 'contract IBanditTreasury', type: 'address' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'treasuryReserve',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContract}__ with `abi` set to __{@link banditTreasuryABI}__.
 */
export function useBanditTreasury(
  config: Omit<UseContractConfig, 'abi'> = {} as any,
) {
  return useContract({ abi: banditTreasuryABI, ...config })
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link banditTreasuryABI}__.
 */
export function useBanditTreasuryRead<TFunctionName extends string>(
  config: Omit<
    UseContractReadConfig<typeof banditTreasuryABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return useContractRead({
    abi: banditTreasuryABI,
    ...config,
  } as UseContractReadConfig<typeof banditTreasuryABI, TFunctionName>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"manager"`.
 */
export function useBanditTreasuryManager(
  config: Omit<
    UseContractReadConfig<typeof banditTreasuryABI, 'manager'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: banditTreasuryABI,
    functionName: 'manager',
    ...config,
  } as UseContractReadConfig<typeof banditTreasuryABI, 'manager'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"withdrawers"`.
 */
export function useBanditTreasuryWithdrawers(
  config: Omit<
    UseContractReadConfig<typeof banditTreasuryABI, 'withdrawers'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: banditTreasuryABI,
    functionName: 'withdrawers',
    ...config,
  } as UseContractReadConfig<typeof banditTreasuryABI, 'withdrawers'>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__.
 */
export function useBanditTreasuryWrite<
  TMode extends WriteContractMode,
  TFunctionName extends string,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof banditTreasuryABI, string>['abi'],
        TFunctionName
      >
    : UseContractWriteConfig<TMode, typeof banditTreasuryABI, TFunctionName> & {
        abi?: never
      } = {} as any,
) {
  return useContractWrite<TMode, typeof banditTreasuryABI, TFunctionName>({
    abi: banditTreasuryABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"setManager"`.
 */
export function useBanditTreasurySetManager<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof banditTreasuryABI,
          'setManager'
        >['abi'],
        'setManager'
      > & { functionName?: 'setManager' }
    : UseContractWriteConfig<TMode, typeof banditTreasuryABI, 'setManager'> & {
        abi?: never
        functionName?: 'setManager'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof banditTreasuryABI, 'setManager'>({
    abi: banditTreasuryABI,
    functionName: 'setManager',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"setWithdrawer"`.
 */
export function useBanditTreasurySetWithdrawer<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof banditTreasuryABI,
          'setWithdrawer'
        >['abi'],
        'setWithdrawer'
      > & { functionName?: 'setWithdrawer' }
    : UseContractWriteConfig<
        TMode,
        typeof banditTreasuryABI,
        'setWithdrawer'
      > & {
        abi?: never
        functionName?: 'setWithdrawer'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof banditTreasuryABI, 'setWithdrawer'>({
    abi: banditTreasuryABI,
    functionName: 'setWithdrawer',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"withdraw"`.
 */
export function useBanditTreasuryWithdraw<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof banditTreasuryABI, 'withdraw'>['abi'],
        'withdraw'
      > & { functionName?: 'withdraw' }
    : UseContractWriteConfig<TMode, typeof banditTreasuryABI, 'withdraw'> & {
        abi?: never
        functionName?: 'withdraw'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof banditTreasuryABI, 'withdraw'>({
    abi: banditTreasuryABI,
    functionName: 'withdraw',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"withdrawEth"`.
 */
export function useBanditTreasuryWithdrawEth<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof banditTreasuryABI,
          'withdrawEth'
        >['abi'],
        'withdrawEth'
      > & { functionName?: 'withdrawEth' }
    : UseContractWriteConfig<TMode, typeof banditTreasuryABI, 'withdrawEth'> & {
        abi?: never
        functionName?: 'withdrawEth'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof banditTreasuryABI, 'withdrawEth'>({
    abi: banditTreasuryABI,
    functionName: 'withdrawEth',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__.
 */
export function usePrepareBanditTreasuryWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof banditTreasuryABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: banditTreasuryABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof banditTreasuryABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"setManager"`.
 */
export function usePrepareBanditTreasurySetManager(
  config: Omit<
    UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'setManager'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: banditTreasuryABI,
    functionName: 'setManager',
    ...config,
  } as UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'setManager'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"setWithdrawer"`.
 */
export function usePrepareBanditTreasurySetWithdrawer(
  config: Omit<
    UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'setWithdrawer'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: banditTreasuryABI,
    functionName: 'setWithdrawer',
    ...config,
  } as UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'setWithdrawer'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"withdraw"`.
 */
export function usePrepareBanditTreasuryWithdraw(
  config: Omit<
    UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'withdraw'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: banditTreasuryABI,
    functionName: 'withdraw',
    ...config,
  } as UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'withdraw'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link banditTreasuryABI}__ and `functionName` set to `"withdrawEth"`.
 */
export function usePrepareBanditTreasuryWithdrawEth(
  config: Omit<
    UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'withdrawEth'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: banditTreasuryABI,
    functionName: 'withdrawEth',
    ...config,
  } as UsePrepareContractWriteConfig<typeof banditTreasuryABI, 'withdrawEth'>)
}

/**
 * Wraps __{@link useContract}__ with `abi` set to __{@link dumpingBanditsABI}__.
 */
export function useDumpingBandits(
  config: Omit<UseContractConfig, 'abi'> = {} as any,
) {
  return useContract({ abi: dumpingBanditsABI, ...config })
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__.
 */
export function useDumpingBanditsRead<TFunctionName extends string>(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, TFunctionName>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"balanceOf"`.
 */
export function useDumpingBanditsBalanceOf(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'balanceOf'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'balanceOf',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'balanceOf'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"everyoneWinsProbability"`.
 */
export function useDumpingBanditsEveryoneWinsProbability(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'everyoneWinsProbability'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'everyoneWinsProbability',
    ...config,
  } as UseContractReadConfig<
    typeof dumpingBanditsABI,
    'everyoneWinsProbability'
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"finalizerReward"`.
 */
export function useDumpingBanditsFinalizerReward(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'finalizerReward'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'finalizerReward',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'finalizerReward'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"getApproved"`.
 */
export function useDumpingBanditsGetApproved(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'getApproved'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'getApproved',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'getApproved'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"getOwnerTokenIds"`.
 */
export function useDumpingBanditsGetOwnerTokenIds(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'getOwnerTokenIds'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'getOwnerTokenIds',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'getOwnerTokenIds'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"isApprovedForAll"`.
 */
export function useDumpingBanditsIsApprovedForAll(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'isApprovedForAll'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'isApprovedForAll',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'isApprovedForAll'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"lastRoundLastTokenId"`.
 */
export function useDumpingBanditsLastRoundLastTokenId(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'lastRoundLastTokenId'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'lastRoundLastTokenId',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'lastRoundLastTokenId'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"minDuration"`.
 */
export function useDumpingBanditsMinDuration(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'minDuration'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'minDuration',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'minDuration'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"name"`.
 */
export function useDumpingBanditsName(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'name'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'name',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'name'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"owner"`.
 */
export function useDumpingBanditsOwner(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'owner'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'owner',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'owner'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"ownerOf"`.
 */
export function useDumpingBanditsOwnerOf(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'ownerOf'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'ownerOf',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'ownerOf'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"price"`.
 */
export function useDumpingBanditsPrice(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'price'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'price',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'price'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"prizeRank"`.
 */
export function useDumpingBanditsPrizeRank(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'prizeRank'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'prizeRank',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'prizeRank'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"prizes"`.
 */
export function useDumpingBanditsPrizes(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'prizes'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'prizes',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'prizes'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"rc"`.
 */
export function useDumpingBanditsRc(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'rc'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'rc',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'rc'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"roundId"`.
 */
export function useDumpingBanditsRoundId(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'roundId'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'roundId',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'roundId'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"roundParticipants"`.
 */
export function useDumpingBanditsRoundParticipants(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'roundParticipants'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'roundParticipants',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'roundParticipants'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"roundStartedAt"`.
 */
export function useDumpingBanditsRoundStartedAt(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'roundStartedAt'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'roundStartedAt',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'roundStartedAt'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"rounds"`.
 */
export function useDumpingBanditsRounds(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'rounds'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'rounds',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'rounds'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"supportsInterface"`.
 */
export function useDumpingBanditsSupportsInterface(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'supportsInterface'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'supportsInterface',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'supportsInterface'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"symbol"`.
 */
export function useDumpingBanditsSymbol(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'symbol'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'symbol',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'symbol'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"tokenIdRound"`.
 */
export function useDumpingBanditsTokenIdRound(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'tokenIdRound'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'tokenIdRound',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'tokenIdRound'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"tokenInfo"`.
 */
export function useDumpingBanditsTokenInfo(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'tokenInfo'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'tokenInfo',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'tokenInfo'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"tokenURI"`.
 */
export function useDumpingBanditsTokenUri(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'tokenURI'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'tokenURI',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'tokenURI'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"treasury"`.
 */
export function useDumpingBanditsTreasury(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'treasury'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'treasury',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'treasury'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"treasuryReserve"`.
 */
export function useDumpingBanditsTreasuryReserve(
  config: Omit<
    UseContractReadConfig<typeof dumpingBanditsABI, 'treasuryReserve'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: dumpingBanditsABI,
    functionName: 'treasuryReserve',
    ...config,
  } as UseContractReadConfig<typeof dumpingBanditsABI, 'treasuryReserve'>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__.
 */
export function useDumpingBanditsWrite<
  TMode extends WriteContractMode,
  TFunctionName extends string,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof dumpingBanditsABI, string>['abi'],
        TFunctionName
      >
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, TFunctionName> & {
        abi?: never
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, TFunctionName>({
    abi: dumpingBanditsABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"approve"`.
 */
export function useDumpingBanditsApprove<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof dumpingBanditsABI, 'approve'>['abi'],
        'approve'
      > & { functionName?: 'approve' }
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, 'approve'> & {
        abi?: never
        functionName?: 'approve'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'approve'>({
    abi: dumpingBanditsABI,
    functionName: 'approve',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"finalizeRound"`.
 */
export function useDumpingBanditsFinalizeRound<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'finalizeRound'
        >['abi'],
        'finalizeRound'
      > & { functionName?: 'finalizeRound' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'finalizeRound'
      > & {
        abi?: never
        functionName?: 'finalizeRound'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'finalizeRound'>({
    abi: dumpingBanditsABI,
    functionName: 'finalizeRound',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"participate"`.
 */
export function useDumpingBanditsParticipate<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'participate'
        >['abi'],
        'participate'
      > & { functionName?: 'participate' }
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, 'participate'> & {
        abi?: never
        functionName?: 'participate'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'participate'>({
    abi: dumpingBanditsABI,
    functionName: 'participate',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"safeTransferFrom"`.
 */
export function useDumpingBanditsSafeTransferFrom<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'safeTransferFrom'
        >['abi'],
        'safeTransferFrom'
      > & { functionName?: 'safeTransferFrom' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'safeTransferFrom'
      > & {
        abi?: never
        functionName?: 'safeTransferFrom'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'safeTransferFrom'>({
    abi: dumpingBanditsABI,
    functionName: 'safeTransferFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setApprovalForAll"`.
 */
export function useDumpingBanditsSetApprovalForAll<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setApprovalForAll'
        >['abi'],
        'setApprovalForAll'
      > & { functionName?: 'setApprovalForAll' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'setApprovalForAll'
      > & {
        abi?: never
        functionName?: 'setApprovalForAll'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'setApprovalForAll'>(
    {
      abi: dumpingBanditsABI,
      functionName: 'setApprovalForAll',
      ...config,
    } as any,
  )
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setEveryoneWinsProbability"`.
 */
export function useDumpingBanditsSetEveryoneWinsProbability<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setEveryoneWinsProbability'
        >['abi'],
        'setEveryoneWinsProbability'
      > & { functionName?: 'setEveryoneWinsProbability' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'setEveryoneWinsProbability'
      > & {
        abi?: never
        functionName?: 'setEveryoneWinsProbability'
      } = {} as any,
) {
  return useContractWrite<
    TMode,
    typeof dumpingBanditsABI,
    'setEveryoneWinsProbability'
  >({
    abi: dumpingBanditsABI,
    functionName: 'setEveryoneWinsProbability',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setFinalizerReward"`.
 */
export function useDumpingBanditsSetFinalizerReward<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setFinalizerReward'
        >['abi'],
        'setFinalizerReward'
      > & { functionName?: 'setFinalizerReward' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'setFinalizerReward'
      > & {
        abi?: never
        functionName?: 'setFinalizerReward'
      } = {} as any,
) {
  return useContractWrite<
    TMode,
    typeof dumpingBanditsABI,
    'setFinalizerReward'
  >({
    abi: dumpingBanditsABI,
    functionName: 'setFinalizerReward',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setMinDuration"`.
 */
export function useDumpingBanditsSetMinDuration<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setMinDuration'
        >['abi'],
        'setMinDuration'
      > & { functionName?: 'setMinDuration' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'setMinDuration'
      > & {
        abi?: never
        functionName?: 'setMinDuration'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'setMinDuration'>({
    abi: dumpingBanditsABI,
    functionName: 'setMinDuration',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setOwner"`.
 */
export function useDumpingBanditsSetOwner<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof dumpingBanditsABI, 'setOwner'>['abi'],
        'setOwner'
      > & { functionName?: 'setOwner' }
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, 'setOwner'> & {
        abi?: never
        functionName?: 'setOwner'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'setOwner'>({
    abi: dumpingBanditsABI,
    functionName: 'setOwner',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setPrice"`.
 */
export function useDumpingBanditsSetPrice<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof dumpingBanditsABI, 'setPrice'>['abi'],
        'setPrice'
      > & { functionName?: 'setPrice' }
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, 'setPrice'> & {
        abi?: never
        functionName?: 'setPrice'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'setPrice'>({
    abi: dumpingBanditsABI,
    functionName: 'setPrice',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setPrizes"`.
 */
export function useDumpingBanditsSetPrizes<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setPrizes'
        >['abi'],
        'setPrizes'
      > & { functionName?: 'setPrizes' }
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, 'setPrizes'> & {
        abi?: never
        functionName?: 'setPrizes'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'setPrizes'>({
    abi: dumpingBanditsABI,
    functionName: 'setPrizes',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setRandomnessClient"`.
 */
export function useDumpingBanditsSetRandomnessClient<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setRandomnessClient'
        >['abi'],
        'setRandomnessClient'
      > & { functionName?: 'setRandomnessClient' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'setRandomnessClient'
      > & {
        abi?: never
        functionName?: 'setRandomnessClient'
      } = {} as any,
) {
  return useContractWrite<
    TMode,
    typeof dumpingBanditsABI,
    'setRandomnessClient'
  >({
    abi: dumpingBanditsABI,
    functionName: 'setRandomnessClient',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setTreasury"`.
 */
export function useDumpingBanditsSetTreasury<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setTreasury'
        >['abi'],
        'setTreasury'
      > & { functionName?: 'setTreasury' }
    : UseContractWriteConfig<TMode, typeof dumpingBanditsABI, 'setTreasury'> & {
        abi?: never
        functionName?: 'setTreasury'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'setTreasury'>({
    abi: dumpingBanditsABI,
    functionName: 'setTreasury',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setTreasuryReserve"`.
 */
export function useDumpingBanditsSetTreasuryReserve<
  TMode extends WriteContractMode,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'setTreasuryReserve'
        >['abi'],
        'setTreasuryReserve'
      > & { functionName?: 'setTreasuryReserve' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'setTreasuryReserve'
      > & {
        abi?: never
        functionName?: 'setTreasuryReserve'
      } = {} as any,
) {
  return useContractWrite<
    TMode,
    typeof dumpingBanditsABI,
    'setTreasuryReserve'
  >({
    abi: dumpingBanditsABI,
    functionName: 'setTreasuryReserve',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"transferFrom"`.
 */
export function useDumpingBanditsTransferFrom<TMode extends WriteContractMode>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof dumpingBanditsABI,
          'transferFrom'
        >['abi'],
        'transferFrom'
      > & { functionName?: 'transferFrom' }
    : UseContractWriteConfig<
        TMode,
        typeof dumpingBanditsABI,
        'transferFrom'
      > & {
        abi?: never
        functionName?: 'transferFrom'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof dumpingBanditsABI, 'transferFrom'>({
    abi: dumpingBanditsABI,
    functionName: 'transferFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__.
 */
export function usePrepareDumpingBanditsWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"approve"`.
 */
export function usePrepareDumpingBanditsApprove(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'approve'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'approve',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'approve'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"finalizeRound"`.
 */
export function usePrepareDumpingBanditsFinalizeRound(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'finalizeRound'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'finalizeRound',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'finalizeRound'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"participate"`.
 */
export function usePrepareDumpingBanditsParticipate(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'participate'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'participate',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'participate'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"safeTransferFrom"`.
 */
export function usePrepareDumpingBanditsSafeTransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'safeTransferFrom'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'safeTransferFrom',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'safeTransferFrom'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setApprovalForAll"`.
 */
export function usePrepareDumpingBanditsSetApprovalForAll(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof dumpingBanditsABI,
      'setApprovalForAll'
    >,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setApprovalForAll',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'setApprovalForAll'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setEveryoneWinsProbability"`.
 */
export function usePrepareDumpingBanditsSetEveryoneWinsProbability(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof dumpingBanditsABI,
      'setEveryoneWinsProbability'
    >,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setEveryoneWinsProbability',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'setEveryoneWinsProbability'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setFinalizerReward"`.
 */
export function usePrepareDumpingBanditsSetFinalizerReward(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof dumpingBanditsABI,
      'setFinalizerReward'
    >,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setFinalizerReward',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'setFinalizerReward'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setMinDuration"`.
 */
export function usePrepareDumpingBanditsSetMinDuration(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setMinDuration'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setMinDuration',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'setMinDuration'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setOwner"`.
 */
export function usePrepareDumpingBanditsSetOwner(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setOwner'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setOwner',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setOwner'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setPrice"`.
 */
export function usePrepareDumpingBanditsSetPrice(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setPrice'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setPrice',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setPrice'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setPrizes"`.
 */
export function usePrepareDumpingBanditsSetPrizes(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setPrizes'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setPrizes',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setPrizes'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setRandomnessClient"`.
 */
export function usePrepareDumpingBanditsSetRandomnessClient(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof dumpingBanditsABI,
      'setRandomnessClient'
    >,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setRandomnessClient',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'setRandomnessClient'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setTreasury"`.
 */
export function usePrepareDumpingBanditsSetTreasury(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setTreasury'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setTreasury',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'setTreasury'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"setTreasuryReserve"`.
 */
export function usePrepareDumpingBanditsSetTreasuryReserve(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof dumpingBanditsABI,
      'setTreasuryReserve'
    >,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'setTreasuryReserve',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof dumpingBanditsABI,
    'setTreasuryReserve'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link dumpingBanditsABI}__ and `functionName` set to `"transferFrom"`.
 */
export function usePrepareDumpingBanditsTransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'transferFrom'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: dumpingBanditsABI,
    functionName: 'transferFrom',
    ...config,
  } as UsePrepareContractWriteConfig<typeof dumpingBanditsABI, 'transferFrom'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__.
 */
export function useDumpingBanditsEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, TEventName>,
    'abi'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"Approval"`.
 */
export function useDumpingBanditsApprovalEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'Approval'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'Approval',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'Approval'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"ApprovalForAll"`.
 */
export function useDumpingBanditsApprovalForAllEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'ApprovalForAll'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'ApprovalForAll',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'ApprovalForAll'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"ParticipantAdded"`.
 */
export function useDumpingBanditsParticipantAddedEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'ParticipantAdded'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'ParticipantAdded',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'ParticipantAdded'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"Redistribution"`.
 */
export function useDumpingBanditsRedistributionEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'Redistribution'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'Redistribution',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'Redistribution'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"RoundFinalized"`.
 */
export function useDumpingBanditsRoundFinalizedEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'RoundFinalized'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'RoundFinalized',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'RoundFinalized'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"RoundStarted"`.
 */
export function useDumpingBanditsRoundStartedEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'RoundStarted'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'RoundStarted',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'RoundStarted'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetEveryoneWinsProbability"`.
 */
export function useDumpingBanditsSetEveryoneWinsProbabilityEvent(
  config: Omit<
    UseContractEventConfig<
      typeof dumpingBanditsABI,
      'SetEveryoneWinsProbability'
    >,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetEveryoneWinsProbability',
    ...config,
  } as UseContractEventConfig<
    typeof dumpingBanditsABI,
    'SetEveryoneWinsProbability'
  >)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetFinalizerReward"`.
 */
export function useDumpingBanditsSetFinalizerRewardEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetFinalizerReward'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetFinalizerReward',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetFinalizerReward'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetMinDuration"`.
 */
export function useDumpingBanditsSetMinDurationEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetMinDuration'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetMinDuration',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetMinDuration'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetOwner"`.
 */
export function useDumpingBanditsSetOwnerEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetOwner'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetOwner',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetOwner'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetPrice"`.
 */
export function useDumpingBanditsSetPriceEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetPrice'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetPrice',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetPrice'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetPrizes"`.
 */
export function useDumpingBanditsSetPrizesEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetPrizes'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetPrizes',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetPrizes'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetRandomnessClient"`.
 */
export function useDumpingBanditsSetRandomnessClientEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetRandomnessClient'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetRandomnessClient',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetRandomnessClient'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetTreasury"`.
 */
export function useDumpingBanditsSetTreasuryEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetTreasury'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetTreasury',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetTreasury'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"SetTreasuryReserve"`.
 */
export function useDumpingBanditsSetTreasuryReserveEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'SetTreasuryReserve'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'SetTreasuryReserve',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'SetTreasuryReserve'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"Transfer"`.
 */
export function useDumpingBanditsTransferEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'Transfer'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'Transfer',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'Transfer'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link dumpingBanditsABI}__ and `eventName` set to `"WonPrize"`.
 */
export function useDumpingBanditsWonPrizeEvent(
  config: Omit<
    UseContractEventConfig<typeof dumpingBanditsABI, 'WonPrize'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: dumpingBanditsABI,
    eventName: 'WonPrize',
    ...config,
  } as UseContractEventConfig<typeof dumpingBanditsABI, 'WonPrize'>)
}
