import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Lore from "../components/lore";
import Play from "../components/play";
import Landing from "../components/landing";
import MyBandits from "../components/myBandits";
import Rules from "../components/rules";
import React, { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [roundNumber, setRoundNumber] = useState(1);
  const [activePage, setActivePage] = useState("Play");
  const [pages, setPages] = useState([
    {
      name: "Play",
      component: <Play />,
    },
    {
      name: "Rules",
      component: <Rules />,
    },
    {
      name: "Lore",
      component: <Lore />,
    },
    {
      name: "My Bandits",
      component: <MyBandits />,
    },
  ]);

  return (
    <div className="w-full min-h-screen bg-brand-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full px-20 pt-8 pb-8">
        <Link href="/">
          <div className="relative mt-2 text-lg text-brand-green">
            DUMPING BANDITS
          </div>
        </Link>
        <div className="pl-5">
          {pages.map((page) => {
            return (
              <div>
                <div className="relative mt-2 text-lg text-brand-green">
                  <div
                    className="cursor-pointer"
                    onClick={() => {
                      setActivePage(page.name);
                    }}>
                    {page.name === "Play"
                      ? `Play – Round ${roundNumber}`
                      : page.name}
                  </div>
                  {activePage === page.name && (
                    <div className="absolute flex items-center justify-center w-4 h-4 rounded-full bg-brand-green/20 -left-5 top-1.5 animate-pulse">
                      <div className="w-2 h-2 rounded-full bg-brand-green"></div>
                    </div>
                  )}
                </div>
                <div
                  className={`h-0 ${
                    activePage === page.name && "h-auto"
                  }`}></div>
                {activePage === page.name && page.component}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
